Feature/new bucket functions
SmartcitySantiagoChile/S3FileUploader pull request #2
Opened 2021-08-16 14:57 UTC by Bastianleaf

# Nuevos Comandos
Se agregan dos comandos nuevos que permiten mover archivos entre buckets y eliminar un bucket en su totalidad.

## delete_bucket_from_s3
Comando que permite eliminar un bucket. Este se encarga de eliminar cada archivo del bucket para posteriormente eliminarlo.

## move_bucket_from_s3
Comando que permite mover archivos entre buckets. Por defecto mueve todos los archivos desde el bucket origen al bucket destino. 

Como parámetros opcionales se permite agregar una lista de archivos a ser movidos y una lista de filtros de extensiones a mover.

2021-08-16 20:58 UTC, felipinbombin requested changes

2021-08-16 20:58 UTC, felipinbombin commented on README.md
> +El primer parámetros es el bucket desde donde se copiarán los archivos. El segundo comando es el bucket al que se copiarán los archivos.
está en plural

2021-08-16 20:58 UTC, felipinbombin commented on aws.py
> +                print(f"{file} moved from {source_bucket_name} to {target_bucket_name}")
reemplazar prints por logger.info

2021-08-17 19:06 UTC, Bastianleaf commented on README.md
> +El primer parámetros es el bucket desde donde se copiarán los archivos. El segundo comando es el bucket al que se copiarán los archivos.
Ok

2021-08-17 19:06 UTC, Bastianleaf commented on aws.py
> +                print(f"{file} moved from {source_bucket_name} to {target_bucket_name}")
Ok

2021-08-17 20:11 UTC, Bastianleaf commented
Se realizan los cambios solicitados.

2021-08-17 20:25 UTC, felipinbombin approved these changes

2021-08-17 20:25 UTC, merged